# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('redirect_url', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('comments', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Book')),
            ],
        ),
    ]
