# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
