# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_chapter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='heading',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
